generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Grupo
    theme:            default
    
    list:
      title:        'Llistar Grups'
      display:      [id, nombre, _centro_id_list, _inscription_has_grupo]
      filters:      [nombre, centro_id]
      object_actions:
        _edit:       ~
        _delete:     ~

    edit:
        title: 'Grup %%nombre%%'
        display:
          "General": [nombre, _centro_id, grupo_has_profesors, _inscription_has_grupo]

    fields:
          nombre:     { name: 'Nom' }
          centro_id:  { name: 'Centre' }
          id:  { credentials: [administrador] }
          centro_id_list:  { name: 'Centre' }
          grupo_has_profesors: { name: 'Professors', type: admin_double_list, params: through_class=GrupoHasProfesor }
          inscription_has_grupo: { name: 'Estudiants' }
