<?php
// auto-generated by sfPropelAdmin
// date: 2015/03/30 08:24:55
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editar inscripció', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('Inscription/edit_header', array('inscription' => $inscription)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('Inscription/edit_messages', array('inscription' => $inscription, 'labels' => $labels)) ?>
<?php include_partial('Inscription/edit_form', array('inscription' => $inscription, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('Inscription/edit_footer', array('inscription' => $inscription)) ?>
</div>

</div>

<?php use_javascript('jquery-1.11.2.min.js') ?>

<script type="text/javascript">

    $.noConflict();
    jQuery(document).ready(function($) {
        $('#inscription_student_course_inscription').on('change', function(e) {
            updateServices($('#inscription_student_course_inscription').val(), 2);
        });

        function updateServices(idCentre, type)
        {
            if (idCentre) {
                $.ajax({
                    url: '<?php echo url_for('Inscription/serviceSchedulesCourse'); ?>',
                    data: 'id=' + idCentre + '&type=' + type,
                    success: function(data) {
                        if (type == 1) {
                            if (data.length) {
                                var values = data.split('|');
                                $("#unassociated_inscription_service_schedule > option").toggle(true);
                                $("#unassociated_inscription_service_schedule > option").each(function () {
                                    if (values.indexOf($(this).attr('value')) == -1) {
                                        $(this).toggle(false);
                                    }
                                });

                                $("#associated_inscription_service_schedule > option").toggle(true);
                                $("#associated_inscription_service_schedule > option").each(function () {
                                    if (values.indexOf($(this).attr('value')) == -1) {
                                        $(this).toggle(false);
                                    }
                                });
                            }
                            else {
                                $("#unassociated_inscription_service_schedule > option").toggle(false);
                                $("#associated_inscription_service_schedule > option").toggle(false);
                            }
                        }
                        else {
                            if (data.length)
                            {
                                $("#associated_inscription_service_schedule > option").remove();
                                $("#unassociated_inscription_service_schedule").html(data);
                            }
                            else {
                                $("#unassociated_inscription_service_schedule > option").remove();
                                $("#associated_inscription_service_schedule > option").remove();
                            }
                        }
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
            }
        }

        updateServices($('#inscription_student_course_inscription').val(), 1);
        
        function addValidation(){
            $('#inscription_student_name').attr('required', 'required');
            $('#inscription_student_primer_apellido').attr('required', 'required');
            $('#inscription_student_segundo_apellido').attr('required', 'required');
            $('#inscription_student_birth_date').attr('required', 'required');
            $('#inscription_student_address').attr('required', 'required');
            $('#inscription_student_zip').attr('required', 'required');
            $('#inscription_student_city').attr('required', 'required');
            $('#inscription_student_provincia').attr('required', 'required');
            $('#inscription_student_school_year').attr('required', 'required');
            $('#inscription_kids_and_us_center_id').attr('required', 'required');
            $('#inscription_summer_fun_center_id').attr('required', 'required');
            $('#inscription_school_year_id').attr('required', 'required');
            $('#inscription_student_num_tarjeta_sanitaria').attr('required', 'required');
            $('#inscription_student_tarjeta_sanitaria_companyia').attr('required', 'required');
        }
        
        function addFatherValidation(){
            $('#inscription_father_name').attr('required', 'required');
            $('#inscription_father_primer_apellido').attr('required', 'required');
            $('#inscription_father_phone').attr('required', 'required');
            $('#inscription_father_dni').attr('required', 'required');
            $('#inscription_father_mail').attr('required', 'required');
        }
        
        function removeFatherValidation(){
            $('#inscription_father_name').removeAttr('required');
            $('#inscription_father_primer_apellido').removeAttr('required');
            $('#inscription_father_phone').removeAttr('required');
            $('#inscription_father_dni').removeAttr('required');
            $('#inscription_father_mail').removeAttr('required');
        }
        
        function addMotherValidation(){
            $('#inscription_mother_name').attr('required', 'required');
            $('#inscription_mother_primer_apellido').attr('required', 'required');
            $('#inscription_mother_phone').attr('required', 'required');
            $('#inscription_mother_dni').attr('required', 'required');
            $('#inscription_mother_mail').attr('required', 'required');
        }
        
        function removeMotherValidation(){
            $('#inscription_mother_name').removeAttr('required');
            $('#inscription_mother_primer_apellido').removeAttr('required');
            $('#inscription_mother_phone').removeAttr('required');
            $('#inscription_mother_dni').removeAttr('required');
            $('#inscription_mother_mail').removeAttr('required');
        }
        
        addValidation();
        addFatherValidation();
        addMotherValidation();
        
        $('#inscription_is_father_mail_main').click(function(){
            if(document.getElementById('inscription_is_father_mail_main').checked){
                addFatherValidation();
            }else{
                removeFatherValidation();
            }
        });
        
        $('#inscription_is_mother_mail_main').click(function(){
            if(document.getElementById('inscription_is_mother_mail_main').checked){
                addMotherValidation();
            }else{
                removeMotherValidation();
            }
        });
        
    });


</script>
