<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/02 12:40:09
?>
<?php if ($sf_request->getError('delete')): ?>
<div class="form-errors">
  <h2><?php echo __('Could not delete the selected %name%', array('%name%' => 'Course')) ?></h2>
  <ul>
    <li><?php echo __('Could not delete the selected Course. Make sure it does not have any associated items.') ?></li>
  </ul>
</div>
<?php endif; ?>
