<?php
// auto-generated by sfPropelAdmin
// date: 2015/03/25 09:30:20
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Setmana %%_summer_fun_center_id_list%%',
array('%%_summer_fun_center_id_list%%' => get_partial('summer_fun_center_id_list', array('type' => 'list', 'course' => $course)))) ?></h1>

<div id="sf_admin_header">
<?php include_partial('course/edit_header', array('course' => $course)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('course/edit_messages', array('course' => $course, 'labels' => $labels)) ?>
<?php include_partial('course/edit_form', array('course' => $course, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('course/edit_footer', array('course' => $course)) ?>
</div>

</div>

<?php use_javascript('jquery-1.11.2.min.js') ?>

<script type="text/javascript">

    $.noConflict();
    jQuery(document).ready(function($) {
        $('#course_summer_fun_center_id').on('change', function(e) {
            updateServices($('#course_summer_fun_center_id').val(), 2);
        });

        function updateServices(idCentre, type)
        {
            if (idCentre) {
                $.ajax({
                    url: '<?php echo url_for('course/servicesCentre'); ?>',
                    data: 'id=' + idCentre + '&type=' + type,
                    success: function(data) {
                        if (type == 1) {
                            if (data.length) {
                                var values = data.split('|');
                                $("#unassociated_course_has_services > option").toggle(true);
                                $("#unassociated_course_has_services > option").each(function () {
                                    if (values.indexOf($(this).attr('value')) == -1) {
                                        $(this).toggle(false);
                                    }
                                });

                                $("#associated_course_has_services > option").toggle(true);
                                $("#associated_course_has_services > option").each(function () {
                                    if (values.indexOf($(this).attr('value')) == -1) {
                                        $(this).toggle(false);
                                    }
                                });
                            }
                            else {
                                $("#unassociated_course_has_services > option").toggle(false);
                                $("#associated_course_has_services > option").toggle(false);
                            }
                        }
                        else {
                            if (data.length)
                            {
                                $("#associated_course_has_services > option").remove();
                                $("#unassociated_course_has_services").html(data);
                            }
                            else {
                                $("#unassociated_course_has_services > option").remove();
                                $("#associated_course_has_services > option").remove();
                            }
                        }
                    },
                    error: function(data) {
                        console.log(data);
                    }
                });
            }
        }

        updateServices($('#course_summer_fun_center_id').val(), 1);
    });


</script>