<?php
// auto-generated by sfPropelAdmin
// date: 2018/02/04 18:28:20
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>
<style>
    .form-errors li {
        padding: 5px 20px!important;
        background: none!important;
        list-style: none!important;
    }
</style>
<div id="sf_admin_container">

<h1><?php echo __('Llistar Setmanes', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('course/list_header', array('pager' => $pager)) ?>
<?php include_partial('course/list_messages', array('pager' => $pager)) ?>
</div>

<div id="sf_admin_bar">
<?php include_partial('filters', array('filters' => $filters)) ?>
</div>

<div id="sf_admin_content">
    
<?php if ($sf_flash->has('notice')): ?>
<div class="save-ok">
<h2><?php echo __($sf_flash->get('notice')) ?></h2>
</div>
<?php endif; ?>
    
<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('course/list', array('pager' => $pager)) ?>
<?php endif; ?>
<?php include_partial('list_actions') ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('course/list_footer', array('pager' => $pager)) ?>
</div>

</div>
