listSuccess:
  javascripts: [accounting-v1.js, jquery-ui/jquery-1.10.2.js, jquery-ui/jquery-ui-1.10.4.custom.min.js, -/sfAdminDashPlugin/js/jquery-1.3.1.min.js]
  stylesheets: [accounting.css, /sf/sf_admin/css/main.css, ui-lightness/jquery-ui-1.10.4.custom.min.css]