<?php
// auto-generated by sfPropelAdmin
// date: 2016/03/22 17:57:14
?>
<?php echo form_tag('summer_fun_zone_center/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'double_list_submit(); return true;'
)) ?>

<?php echo object_input_hidden_tag($summer_fun_center, 'getId') ?>

<fieldset id="sf_fieldset_general" class="">
<h2><?php echo __('General') ?></h2>


    <?php if ($sf_user->hasCredential(array (   0 => 'administrador', ))): ?>
<div class="form-row">
  <?php echo label_for('summer_fun_center[summer_fun_zone_id]', __($labels['summer_fun_center{summer_fun_zone_id}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{summer_fun_zone_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{summer_fun_zone_id}')): ?>
    <?php echo form_error('summer_fun_center{summer_fun_zone_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($summer_fun_center, 'getSummerFunZoneId', array (
  'related_class' => 'SummerFunZone',
  'control_name' => 'summer_fun_center[summer_fun_zone_id]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
    <?php endif; ?>

    <?php if ($sf_user->hasCredential(array (   0 => 'administrador', ))): ?>
<div class="form-row">
  <?php echo label_for('summer_fun_center[summer_fun_center_has_profile]', __($labels['summer_fun_center{summer_fun_center_has_profile}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{summer_fun_center_has_profile}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{summer_fun_center_has_profile}')): ?>
    <?php echo form_error('summer_fun_center{summer_fun_center_has_profile}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_double_list($summer_fun_center, 'getSummerFunCenterHasProfile', array (
  'control_name' => 'summer_fun_center[summer_fun_center_has_profile]',
  'through_class' => 'SummerFunCenterHasProfile',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Opcionalment pot assignar un usuari auxiliar per a què pugui editar informació relacionada amb aquest centre. L\'usuari ha de tenir el permís "summer-fun".') ?></div>  </div>
</div>
    <?php endif; ?>

<div class="form-row">
  <?php echo label_for('summer_fun_center[mail]', __($labels['summer_fun_center{mail}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{mail}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{mail}')): ?>
    <?php echo form_error('summer_fun_center{mail}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getMail', array (
  'size' => 80,
  'control_name' => 'summer_fun_center[mail]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_inscripcions" class="">
<h2><?php echo __('Inscripcions') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[is_registration_open]', __($labels['summer_fun_center{is_registration_open}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{is_registration_open}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{is_registration_open}')): ?>
    <?php echo form_error('summer_fun_center{is_registration_open}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getIsRegistrationOpen', array (
  'control_name' => 'summer_fun_center[is_registration_open]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>


<div class="form-row">
  <?php echo label_for('summer_fun_center[is_vaccination]', __($labels['summer_fun_center{is_vaccination}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{is_vaccination}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{is_vaccination}')): ?>
    <?php echo form_error('summer_fun_center{is_vaccination}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getIsVaccination', array (
  'control_name' => 'summer_fun_center[is_vaccination]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>



<div class="form-row">
  <?php echo label_for('summer_fun_center[show_excursion_widget]', __($labels['summer_fun_center{show_excursion_widget}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{show_excursion_widget}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{show_excursion_widget}')): ?>
    <?php echo form_error('summer_fun_center{show_excursion_widget}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getShowExcursionWidget', array (
  'control_name' => 'summer_fun_center[show_excursion_widget]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[show_beca_widget]', __($labels['summer_fun_center{show_beca_widget}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{show_beca_widget}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{show_beca_widget}')): ?>
    <?php echo form_error('summer_fun_center{show_beca_widget}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getShowBecaWidget', array (
  'control_name' => 'summer_fun_center[show_beca_widget]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_formes_de_pagament" class="">
<h2><?php echo __('Formes de pagament') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[transfer_payment]', __($labels['summer_fun_center{transfer_payment}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{transfer_payment}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{transfer_payment}')): ?>
    <?php echo form_error('summer_fun_center{transfer_payment}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getTransferPayment', array (
  'control_name' => 'summer_fun_center[transfer_payment]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[account_number]', __($labels['summer_fun_center{account_number}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{account_number}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{account_number}')): ?>
    <?php echo form_error('summer_fun_center{account_number}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getAccountNumber', array (
  'size' => 80,
  'control_name' => 'summer_fun_center[account_number]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('EX: 1234-1234-12-1234567890') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[cash_payment]', __($labels['summer_fun_center{cash_payment}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{cash_payment}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{cash_payment}')): ?>
    <?php echo form_error('summer_fun_center{cash_payment}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getCashPayment', array (
  'control_name' => 'summer_fun_center[cash_payment]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[recibo_domiciliado_payment]', __($labels['summer_fun_center{recibo_domiciliado_payment}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_payment}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_payment}')): ?>
    <?php echo form_error('summer_fun_center{recibo_domiciliado_payment}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getReciboDomiciliadoPayment', array (
  'control_name' => 'summer_fun_center[recibo_domiciliado_payment]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[tpv_payment]', __($labels['summer_fun_center{tpv_payment}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{tpv_payment}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{tpv_payment}')): ?>
    <?php echo form_error('summer_fun_center{tpv_payment}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($summer_fun_center, 'getTpvPayment', array (
  'control_name' => 'summer_fun_center[tpv_payment]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[merchant_code]', __($labels['summer_fun_center{merchant_code}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{merchant_code}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{merchant_code}')): ?>
    <?php echo form_error('summer_fun_center{merchant_code}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getMerchantCode', array (
  'size' => 80,
  'control_name' => 'summer_fun_center[merchant_code]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[merchant_key]', __($labels['summer_fun_center{merchant_key}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{merchant_key}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{merchant_key}')): ?>
    <?php echo form_error('summer_fun_center{merchant_key}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getMerchantKey', array (
  'size' => 80,
  'control_name' => 'summer_fun_center[merchant_key]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[url_tpv]', __($labels['summer_fun_center{url_tpv}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{url_tpv}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{url_tpv}')): ?>
    <?php echo form_error('summer_fun_center{url_tpv}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getUrlTpv', array (
  'size' => 80,
  'control_name' => 'summer_fun_center[url_tpv]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

    <div class="form-row">
        <?php echo label_for('summer_fun_center[address_tpv]', __($labels['summer_fun_center{address_tpv}']), '') ?>
        <div class="content<?php if ($sf_request->hasError('summer_fun_center{address_tpv}')): ?> form-error<?php endif; ?>">
            <?php if ($sf_request->hasError('summer_fun_center{address_tpv}')): ?>
                <?php echo form_error('summer_fun_center{address_tpv}', array('class' => 'form-error-msg')) ?>
            <?php endif; ?>

            <?php $value = object_input_tag($summer_fun_center, 'getAddressTpv', array (
                'size' => 80,
                'control_name' => 'summer_fun_center[address_tpv]',
            )); echo $value ? $value : '&nbsp;' ?>
        </div>
    </div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_date]', __($labels['summer_fun_center{second_payment_date}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_date}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_date}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_date}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($summer_fun_center, 'getSecondPaymentDate', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'summer_fun_center[second_payment_date]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_date]', __($labels['summer_fun_center{second_payment_mailing_date}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_date}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_date}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_date}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($summer_fun_center, 'getSecondPaymentMailingDate', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'summer_fun_center[second_payment_mailing_date]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_descomptes" class="">
<h2><?php echo __('Descomptes') ?></h2>

  <div style="padding:10px;background-color:#fff8c4;border-bottom:1px solid #f2c779;">
    <p><strong><?php echo __('discounts_help_title') ?>: </strong></p>
    <ul style="margin-left:25px">
      <li><?php echo __('discounts_help_1') ?></li>
      <li><?php echo __('discounts_help_2') ?></li>
      <li><?php echo __('discounts_help_3') ?></li>
    </ul>
  </div>


<div class="form-row">
  <?php echo label_for('summer_fun_center[weeks_discount]', __($labels['summer_fun_center{weeks_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{weeks_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{weeks_discount}')): ?>
    <?php echo form_error('summer_fun_center{weeks_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getWeeksDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[weeks_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('week_discount_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[weeks_percent_discount]', __($labels['summer_fun_center{weeks_percent_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{weeks_percent_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{weeks_percent_discount}')): ?>
    <?php echo form_error('summer_fun_center{weeks_percent_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getWeeksPercentDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[weeks_percent_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('decimal_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[weeks_amount_discount]', __($labels['summer_fun_center{weeks_amount_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{weeks_amount_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{weeks_amount_discount}')): ?>
    <?php echo form_error('summer_fun_center{weeks_amount_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getWeeksAmountDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[weeks_amount_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('decimal_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[brothers_discount]', __($labels['summer_fun_center{brothers_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{brothers_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{brothers_discount}')): ?>
    <?php echo form_error('summer_fun_center{brothers_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getBrothersDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[brothers_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('brothers_discount_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[brothers_percent_discount]', __($labels['summer_fun_center{brothers_percent_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{brothers_percent_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{brothers_percent_discount}')): ?>
    <?php echo form_error('summer_fun_center{brothers_percent_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getBrothersPercentDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[brothers_percent_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('decimal_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[brothers_amount_discount]', __($labels['summer_fun_center{brothers_amount_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{brothers_amount_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{brothers_amount_discount}')): ?>
    <?php echo form_error('summer_fun_center{brothers_amount_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getBrothersAmountDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[brothers_amount_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('decimal_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[student_kids_and_us]', __($labels['summer_fun_center{student_kids_and_us}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{student_kids_and_us}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{student_kids_and_us}')): ?>
    <?php echo form_error('summer_fun_center{student_kids_and_us}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('student_kids_and_us', array('type' => 'edit', 'summer_fun_center' => $summer_fun_center)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[kids_and_us_student_percent_discount]', __($labels['summer_fun_center{kids_and_us_student_percent_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{kids_and_us_student_percent_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{kids_and_us_student_percent_discount}')): ?>
    <?php echo form_error('summer_fun_center{kids_and_us_student_percent_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getKidsAndUsStudentPercentDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[kids_and_us_student_percent_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('decimal_help') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[kids_and_us_student_amount_discount]', __($labels['summer_fun_center{kids_and_us_student_amount_discount}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{kids_and_us_student_amount_discount}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{kids_and_us_student_amount_discount}')): ?>
    <?php echo form_error('summer_fun_center{kids_and_us_student_amount_discount}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getKidsAndUsStudentAmountDiscount', array (
  'size' => 7,
  'control_name' => 'summer_fun_center[kids_and_us_student_amount_discount]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('decimal_help') ?></div>  </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_catal__" class="">
<h2><?php echo __('Català') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[title_ca]', __($labels['summer_fun_center{title_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{title_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{title_ca}')): ?>
    <?php echo form_error('summer_fun_center{title_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getTitleCa', array (
  'control_name' => 'summer_fun_center[title_ca]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[description_ca]', __($labels['summer_fun_center{description_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{description_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{description_ca}')): ?>
    <?php echo form_error('summer_fun_center{description_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getDescriptionCa', array (
  'control_name' => 'summer_fun_center[description_ca]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[docs_ca]', __($labels['summer_fun_center{docs_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{docs_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{docs_ca}')): ?>
    <?php echo form_error('summer_fun_center{docs_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('docs_ca', array('type' => 'edit', 'summer_fun_center' => $summer_fun_center)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Màxim 10 documents. Format PDF o DOC. Pes màxim 2 MB.') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_confirmation_mail_ca]', __($labels['summer_fun_center{inscription_confirmation_mail_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_ca}')): ?>
    <?php echo form_error('summer_fun_center{inscription_confirmation_mail_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getInscriptionConfirmationMailCa', array (
  'control_name' => 'summer_fun_center[inscription_confirmation_mail_ca]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_conditions_terms_pdf_ca]', __($labels['summer_fun_center{inscription_conditions_terms_pdf_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_ca}')): ?>
    <?php echo form_error('summer_fun_center{inscription_conditions_terms_pdf_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($summer_fun_center, 'getInscriptionConditionsTermsPdfCa', array (
  'control_name' => 'summer_fun_center[inscription_conditions_terms_pdf_ca]',
  'include_link' => 'summer-fun/center/pdf-conditions/ca',
  'include_text' => 'veure pdf',
  'include_remove' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_question_ca]', __($labels['summer_fun_center{custom_question_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_question_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_question_ca}')): ?>
    <?php echo form_error('summer_fun_center{custom_question_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getCustomQuestionCa', array (
  'control_name' => 'summer_fun_center[custom_question_ca]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[recibo_domiciliado_txt_ca]', __($labels['summer_fun_center{recibo_domiciliado_txt_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_ca}')): ?>
    <?php echo form_error('summer_fun_center{recibo_domiciliado_txt_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getReciboDomiciliadoTxtCa', array (
  'control_name' => 'summer_fun_center[recibo_domiciliado_txt_ca]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_ca]', __($labels['summer_fun_center{second_payment_mailing_body_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_ca}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyCa', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_ca]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_no_tpv_ca]', __($labels['summer_fun_center{second_payment_mailing_body_no_tpv_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_ca}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_no_tpv_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyNoTpvCa', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_no_tpv_ca]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_discount_ca]', __($labels['summer_fun_center{custom_discount_ca}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_discount_ca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_discount_ca}')): ?>
    <?php echo form_error('summer_fun_center{custom_discount_ca}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getCustomDiscountCa', array (
  'control_name' => 'summer_fun_center[custom_discount_ca]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_castellano" class="">
<h2><?php echo __('Castellano') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[title_es]', __($labels['summer_fun_center{title_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{title_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{title_es}')): ?>
    <?php echo form_error('summer_fun_center{title_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getTitleEs', array (
  'control_name' => 'summer_fun_center[title_es]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[description_es]', __($labels['summer_fun_center{description_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{description_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{description_es}')): ?>
    <?php echo form_error('summer_fun_center{description_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getDescriptionEs', array (
  'control_name' => 'summer_fun_center[description_es]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[docs_es]', __($labels['summer_fun_center{docs_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{docs_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{docs_es}')): ?>
    <?php echo form_error('summer_fun_center{docs_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('docs_es', array('type' => 'edit', 'summer_fun_center' => $summer_fun_center)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Màxim 10 documents. Format PDF o DOC. Pes màxim 2 MB.') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_confirmation_mail_es]', __($labels['summer_fun_center{inscription_confirmation_mail_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_es}')): ?>
    <?php echo form_error('summer_fun_center{inscription_confirmation_mail_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getInscriptionConfirmationMailEs', array (
  'control_name' => 'summer_fun_center[inscription_confirmation_mail_es]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_conditions_terms_pdf_es]', __($labels['summer_fun_center{inscription_conditions_terms_pdf_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_es}')): ?>
    <?php echo form_error('summer_fun_center{inscription_conditions_terms_pdf_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($summer_fun_center, 'getInscriptionConditionsTermsPdfEs', array (
  'control_name' => 'summer_fun_center[inscription_conditions_terms_pdf_es]',
  'include_link' => 'summer-fun/center/pdf-conditions/es',
  'include_text' => 'veure pdf',
  'include_remove' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_question_es]', __($labels['summer_fun_center{custom_question_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_question_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_question_es}')): ?>
    <?php echo form_error('summer_fun_center{custom_question_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getCustomQuestionEs', array (
  'control_name' => 'summer_fun_center[custom_question_es]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[recibo_domiciliado_txt_es]', __($labels['summer_fun_center{recibo_domiciliado_txt_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_es}')): ?>
    <?php echo form_error('summer_fun_center{recibo_domiciliado_txt_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getReciboDomiciliadoTxtEs', array (
  'control_name' => 'summer_fun_center[recibo_domiciliado_txt_es]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_es]', __($labels['summer_fun_center{second_payment_mailing_body_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_es}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyEs', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_es]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_no_tpv_es]', __($labels['summer_fun_center{second_payment_mailing_body_no_tpv_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_es}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_no_tpv_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyNoTpvEs', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_no_tpv_es]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_discount_es]', __($labels['summer_fun_center{custom_discount_es}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_discount_es}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_discount_es}')): ?>
    <?php echo form_error('summer_fun_center{custom_discount_es}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getCustomDiscountEs', array (
  'control_name' => 'summer_fun_center[custom_discount_es]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_italiano" class="">
<h2><?php echo __('Italiano') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[title_it]', __($labels['summer_fun_center{title_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{title_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{title_it}')): ?>
    <?php echo form_error('summer_fun_center{title_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getTitleIt', array (
  'control_name' => 'summer_fun_center[title_it]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[description_it]', __($labels['summer_fun_center{description_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{description_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{description_it}')): ?>
    <?php echo form_error('summer_fun_center{description_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getDescriptionIt', array (
  'control_name' => 'summer_fun_center[description_it]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[docs_it]', __($labels['summer_fun_center{docs_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{docs_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{docs_it}')): ?>
    <?php echo form_error('summer_fun_center{docs_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('docs_it', array('type' => 'edit', 'summer_fun_center' => $summer_fun_center)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Màxim 10 documents. Format PDF o DOC. Pes màxim 2 MB.') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_confirmation_mail_it]', __($labels['summer_fun_center{inscription_confirmation_mail_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_it}')): ?>
    <?php echo form_error('summer_fun_center{inscription_confirmation_mail_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getInscriptionConfirmationMailIt', array (
  'control_name' => 'summer_fun_center[inscription_confirmation_mail_it]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_conditions_terms_pdf_it]', __($labels['summer_fun_center{inscription_conditions_terms_pdf_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_it}')): ?>
    <?php echo form_error('summer_fun_center{inscription_conditions_terms_pdf_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($summer_fun_center, 'getInscriptionConditionsTermsPdfIt', array (
  'control_name' => 'summer_fun_center[inscription_conditions_terms_pdf_it]',
  'include_link' => 'summer-fun/center/pdf-conditions/it',
  'include_text' => 'veure pdf',
  'include_remove' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_question_it]', __($labels['summer_fun_center{custom_question_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_question_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_question_it}')): ?>
    <?php echo form_error('summer_fun_center{custom_question_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getCustomQuestionIt', array (
  'control_name' => 'summer_fun_center[custom_question_it]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[recibo_domiciliado_txt_it]', __($labels['summer_fun_center{recibo_domiciliado_txt_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_it}')): ?>
    <?php echo form_error('summer_fun_center{recibo_domiciliado_txt_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getReciboDomiciliadoTxtIt', array (
  'control_name' => 'summer_fun_center[recibo_domiciliado_txt_it]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_it]', __($labels['summer_fun_center{second_payment_mailing_body_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_it}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyIt', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_it]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_no_tpv_it]', __($labels['summer_fun_center{second_payment_mailing_body_no_tpv_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_it}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_no_tpv_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyNoTpvIt', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_no_tpv_it]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_discount_it]', __($labels['summer_fun_center{custom_discount_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_discount_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_discount_it}')): ?>
    <?php echo form_error('summer_fun_center{custom_discount_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getCustomDiscountIt', array (
  'control_name' => 'summer_fun_center[custom_discount_it]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_franc__s" class="">
<h2><?php echo __('Francès') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[title_fr]', __($labels['summer_fun_center{title_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{title_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{title_fr}')): ?>
    <?php echo form_error('summer_fun_center{title_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getTitleFr', array (
  'control_name' => 'summer_fun_center[title_fr]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[description_fr]', __($labels['summer_fun_center{description_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{description_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{description_fr}')): ?>
    <?php echo form_error('summer_fun_center{description_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getDescriptionFr', array (
  'control_name' => 'summer_fun_center[description_fr]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[docs_fr]', __($labels['summer_fun_center{docs_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{docs_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{docs_fr}')): ?>
    <?php echo form_error('summer_fun_center{docs_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('docs_fr', array('type' => 'edit', 'summer_fun_center' => $summer_fun_center)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Màxim 10 documents. Format PDF o DOC. Pes màxim 2 MB.') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_confirmation_mail_fr]', __($labels['summer_fun_center{inscription_confirmation_mail_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_fr}')): ?>
    <?php echo form_error('summer_fun_center{inscription_confirmation_mail_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getInscriptionConfirmationMailFr', array (
  'control_name' => 'summer_fun_center[inscription_confirmation_mail_fr]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_conditions_terms_pdf_fr]', __($labels['summer_fun_center{inscription_conditions_terms_pdf_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_fr}')): ?>
    <?php echo form_error('summer_fun_center{inscription_conditions_terms_pdf_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($summer_fun_center, 'getInscriptionConditionsTermsPdfFr', array (
  'control_name' => 'summer_fun_center[inscription_conditions_terms_pdf_fr]',
  'include_link' => 'summer-fun/center/pdf-conditions/fr',
  'include_text' => 'veure pdf',
  'include_remove' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_question_it]', __($labels['summer_fun_center{custom_question_it}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_question_it}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_question_it}')): ?>
    <?php echo form_error('summer_fun_center{custom_question_it}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getCustomQuestionIt', array (
  'control_name' => 'summer_fun_center[custom_question_it]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[recibo_domiciliado_txt_fr]', __($labels['summer_fun_center{recibo_domiciliado_txt_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_fr}')): ?>
    <?php echo form_error('summer_fun_center{recibo_domiciliado_txt_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getReciboDomiciliadoTxtFr', array (
  'control_name' => 'summer_fun_center[recibo_domiciliado_txt_fr]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_fr]', __($labels['summer_fun_center{second_payment_mailing_body_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_fr}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyFr', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_fr]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_no_tpv_fr]', __($labels['summer_fun_center{second_payment_mailing_body_no_tpv_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_fr}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_no_tpv_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyNoTpvFr', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_no_tpv_fr]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_discount_fr]', __($labels['summer_fun_center{custom_discount_fr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_discount_fr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_discount_fr}')): ?>
    <?php echo form_error('summer_fun_center{custom_discount_fr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getCustomDiscountFr', array (
  'control_name' => 'summer_fun_center[custom_discount_fr]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>
<fieldset id="sf_fieldset_english" class="">
<h2><?php echo __('English') ?></h2>


<div class="form-row">
  <?php echo label_for('summer_fun_center[title_en]', __($labels['summer_fun_center{title_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{title_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{title_en}')): ?>
    <?php echo form_error('summer_fun_center{title_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getTitleEn', array (
  'disabled' => true,
  'control_name' => 'summer_fun_center[title_en]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[description_en]', __($labels['summer_fun_center{description_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{description_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{description_en}')): ?>
    <?php echo form_error('summer_fun_center{description_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getDescriptionEn', array (
  'control_name' => 'summer_fun_center[description_en]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[docs_en]', __($labels['summer_fun_center{docs_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{docs_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{docs_en}')): ?>
    <?php echo form_error('summer_fun_center{docs_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('docs_en', array('type' => 'edit', 'summer_fun_center' => $summer_fun_center)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Màxim 10 documents. Format PDF o DOC. Pes màxim 2 MB.') ?></div>  </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_confirmation_mail_en]', __($labels['summer_fun_center{inscription_confirmation_mail_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_confirmation_mail_en}')): ?>
    <?php echo form_error('summer_fun_center{inscription_confirmation_mail_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getInscriptionConfirmationMailEn', array (
  'control_name' => 'summer_fun_center[inscription_confirmation_mail_en]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[inscription_conditions_terms_pdf_en]', __($labels['summer_fun_center{inscription_conditions_terms_pdf_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{inscription_conditions_terms_pdf_en}')): ?>
    <?php echo form_error('summer_fun_center{inscription_conditions_terms_pdf_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($summer_fun_center, 'getInscriptionConditionsTermsPdfEn', array (
  'control_name' => 'summer_fun_center[inscription_conditions_terms_pdf_en]',
  'include_link' => 'summer-fun/center/pdf-conditions/en',
  'include_text' => 'veure pdf',
  'include_remove' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_question_en]', __($labels['summer_fun_center{custom_question_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_question_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_question_en}')): ?>
    <?php echo form_error('summer_fun_center{custom_question_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getCustomQuestionEn', array (
  'control_name' => 'summer_fun_center[custom_question_en]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[recibo_domiciliado_txt_en]', __($labels['summer_fun_center{recibo_domiciliado_txt_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{recibo_domiciliado_txt_en}')): ?>
    <?php echo form_error('summer_fun_center{recibo_domiciliado_txt_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($summer_fun_center, 'getReciboDomiciliadoTxtEn', array (
  'control_name' => 'summer_fun_center[recibo_domiciliado_txt_en]',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_en]', __($labels['summer_fun_center{second_payment_mailing_body_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_en}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyEn', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_en]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[second_payment_mailing_body_no_tpv_en]', __($labels['summer_fun_center{second_payment_mailing_body_no_tpv_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{second_payment_mailing_body_no_tpv_en}')): ?>
    <?php echo form_error('summer_fun_center{second_payment_mailing_body_no_tpv_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getSecondPaymentMailingBodyNoTpvEn', array (
  'control_name' => 'summer_fun_center[second_payment_mailing_body_no_tpv_en]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('summer_fun_center[custom_discount_en]', __($labels['summer_fun_center{custom_discount_en}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('summer_fun_center{custom_discount_en}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('summer_fun_center{custom_discount_en}')): ?>
    <?php echo form_error('summer_fun_center{custom_discount_en}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($summer_fun_center, 'getCustomDiscountEn', array (
  'control_name' => 'summer_fun_center[custom_discount_en]',
  'size' => '120x6',
  'class' => 'rich',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('summer_fun_center' => $summer_fun_center)) ?>

</form>

<ul class="sf_admin_actions">
      <?php if ($sf_user->hasCredential(array (   0 => 'administrador', ))): ?>
<li class="float-left"><?php if ($summer_fun_center->getId()): ?>
<?php echo button_to(__('delete'), 'summer_fun_zone_center/delete?id='.$summer_fun_center->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>

<?php endif; ?>  </ul>
