<?php
// auto-generated by sfPropelAdmin
// date: 2014/03/26 17:11:20
?>
<?php if ($sf_user->hasCredential(array (   0 => 'administrador', ))): ?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'summer_fun_zone_center/create', array ('class' => 'sf_admin_action_create',)) ?></li>
</ul>
<?php endif ?>
